// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ykCurQVLCKCC_SXfwPthiKarn_l0Jis',
    appId: '1:1024164971268:web:f05eb6e2336fff33010651',
    messagingSenderId: '1024164971268',
    projectId: 'drug-drug',
    authDomain: 'drug-drug.firebaseapp.com',
    storageBucket: 'drug-drug.firebasestorage.app',
    measurementId: 'G-ZR35MEPLRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV5itJP5IFrjLkPRI7VcVNQjJVvhp9Yng',
    appId: '1:1024164971268:android:2b482ad6356198ef010651',
    messagingSenderId: '1024164971268',
    projectId: 'drug-drug',
    storageBucket: 'drug-drug.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMw-Yx-3FYabZntYpVVPMBrzobRJHTNVA',
    appId: '1:1024164971268:ios:7c373a5e6f48f5ef010651',
    messagingSenderId: '1024164971268',
    projectId: 'drug-drug',
    storageBucket: 'drug-drug.firebasestorage.app',
    iosClientId: '1024164971268-j4bkj76t76fpu02omk1jgosev7kk0rbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMw-Yx-3FYabZntYpVVPMBrzobRJHTNVA',
    appId: '1:1024164971268:ios:7c373a5e6f48f5ef010651',
    messagingSenderId: '1024164971268',
    projectId: 'drug-drug',
    storageBucket: 'drug-drug.firebasestorage.app',
    iosClientId: '1024164971268-j4bkj76t76fpu02omk1jgosev7kk0rbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5ykCurQVLCKCC_SXfwPthiKarn_l0Jis',
    appId: '1:1024164971268:web:6522aa0ea580a611010651',
    messagingSenderId: '1024164971268',
    projectId: 'drug-drug',
    authDomain: 'drug-drug.firebaseapp.com',
    storageBucket: 'drug-drug.firebasestorage.app',
    measurementId: 'G-JFWMKP50NS',
  );
}
